data <- read.csv("../../data/eg4_10.csv", stringsAsFactors = FALSE)
attach(data)
model1 <- aov(Height0 ~ plot)
summary(model1)
plot <- as.factor(plot)
model2 <- aov(Height0 ~ plot + DBH)
summary(model2)