library(vegan)
library(pscl)
library(caret)
data(dune)
data(dune.env)
species <- "Achimill"
df <- cbind(dune.env, SpeciesCount = dune[, species])
df$Presence <- ifelse(df$SpeciesCount > 0, 1, 0)
df$Management <- as.factor(df$Management)
table(df$Management, df$Presence)
glm_model <- glm(Presence ~ Management, data = df, family = binomial)
summary(glm_model)
zi_model <- zeroinfl(SpeciesCount ~ Management | 1, data = df, dist = "poisson")
summary(zi_model)
hurdle_model <- hurdle(SpeciesCount ~ Management | 1, data = df, dist = "poisson")
summary(hurdle_model)
pred_glm <- ifelse(predict(glm_model, type = "response") > 0.5, 1, 0)
pred_zi <- ifelse(predict(zi_model, type = "response") > 0.5, 1, 0)
pred_hurdle <- ifelse(predict(hurdle_model, type = "response") > 0.5, 1, 0)
true_labels <- as.factor(df$Presence)
cm_glm <- confusionMatrix(as.factor(pred_glm), reference = true_labels)
cm_zi <- confusionMatrix(as.factor(pred_zi), reference = true_labels)
cm_hurdle <- confusionMatrix(as.factor(pred_hurdle), reference = true_labels)
print(cm_glm)
print(cm_zi)
print(cm_hurdle)

